name: Build Packages

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

permissions:
  contents: write
  id-token: write

env:
  NODE_VERSION: 24.15.0
  NPM_CONFIG_PROVENANCE: true
  
jobs:
  tests:
    uses: ./.github/workflows/playwright.yml

  build:
    runs-on: ubuntu-latest

    needs: tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm install
      - name: Verify Build
        run: npm run build

  pre_release:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm install
      - name: Make Pre-Version
        run: npm version $(node -e "console.log(require('./package.json').version)")-pre.${{ github.run_number }} --no-git-tag-version
      - name: Build Package
        run: npm run build
      - name: Publish Package
        run: npm publish --tag next --provenance
        env:
          NODE_AUTH_TOKEN: "" # explicitly empty to avoid token fallback
          NPM_CONFIG_PROVENANCE: true

  release:
    runs-on: ubuntu-latest

    needs: build

    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm install
      - name: Build Package
        run: npm run build
      - name: Publish Package on npm
        run: npm publish --tag latest --provenance
        env:
          NODE_AUTH_TOKEN: "" # explicitly empty to avoid token fallback
          NPM_CONFIG_PROVENANCE: true
      - name: Create Git Release Tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TAG_PUSH_PAT }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${require(require('path').resolve(process.env.GITHUB_WORKSPACE, 'package.json')).version}`,
              sha: context.sha
            })