name: Publish GitHub Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Build Local Changelog
        run: node tools/release.mjs
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: LOCAL-CHANGELOG.md
          make_latest: 'true'
